name: NuGet Package Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.x.x

    - name: Build solution
      run: dotnet build --configuration Release

    - name: Pack NuGet package
      run: dotnet pack --no-build --output nuget --configuration Release

    - name: Publish NuGet package
      run: dotnet nuget push nuget/*.nupkg --api-key ${{ secrets.NUGKEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
